# This is a config for E2B sandbox template.
# You can use template ID (x9dqu2lxg4n5drl9wsm8) or template name (woody-nestjs-temp) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("woody-nestjs-temp") # Sync sandbox
# sandbox = await AsyncSandbox.create("woody-nestjs-temp") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('woody-nestjs-temp')

team_id = "24d2e668-64e3-46b0-8b42-f2809f48f4bb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "woody-nestjs-temp"
template_id = "x9dqu2lxg4n5drl9wsm8"
